Ask_Wiki/urls.py
from django.urls import path, re_path
from . import views

app_name = "Ask"

urlpatterns =[
    path('', views.index, name="index"),
    path('main/', views.main, name="main"),
    # path('link/<str:link>/', views.link, name="link"),
    re_path(r'^link/(?P<link>[^`]+)/$', views.link, name="link"),
    path('result/',views.result, name="result"), # 결과화면

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('Ask_Wiki.urls')),
    path('admin/', admin.site.urls),
]

config/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">       
    <link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap.min.css' %}"/>        
    <link rel="stylesheet" type="text/css"  href="{% static 'css/global.css' %}"/>        
    {% block link %}
    {% endblock %}
    <title>
        {% block title %}
        {% endblock %}
    </title>    
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" >  
        <img class="navbar-brand" style="width: 30px;" src="{% static 'image/teamlogo.png' %}">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'Ask:index' %}"><b>묻고 위키로 가&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</b><span class="sr-only">(current)</span></a>                        
            <a class="nav-item nav-link active" href="#"><span class="copyright" onclick="document.getElementById('infojs').style.display='block'"><b>만든사람들 & References</b></span></a>                         
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <div id='infojs' class="infototaldiv">    
        <div class="infoinnerpage">           
            <div id="infoneyong">          
                 <br><h5><b>만든사람들 &amp; References</b></h5><br><hr>
                <b>만든사람들</b><br><br>
                Team : 개발자의 협곡<br><br>                
                김정현<br>
                박종선<br>
                박진영<br>
                조규상<br>
                <hr>
                <b>References</b><br><br>            
                Python, Django, Komaran<br>
                Wikipedia OpenAPI<br>
                HTML5, JavaScript, CSS<br>
                Bootstrap, JQuery, Ajax<br>
                Github<br>
                Visual Studio Code<br>
                <hr><br>
                <div class="infoclosediv">
                    <button onclick="document.getElementById('infojs').style.display='none'" id="closebutton">Close</button> 
                </div> 
            </div>
        </div>    
    </div>	

    <div class="div-footer">
        <div class="div-footer-text">
            <b>2019 Training for 4th Industrial Revolution | Open API를 활용한 빅데이터 전처리・시각화 B 반</b><br>
            <b>COPYRIGHT© 2019 개발자의협곡 ALL RIGHT RESERVED</b><br>        
        </div>
    </div>    

    {% block bodyscript %}
    {% endblock %}
    <script src="{% static 'js/global.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>    
</body>
</html>